// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go_gapic. DO NOT EDIT.

package googleads

import (
	"context"
	"fmt"
	"math"
	"net/url"
	"time"

	gax "github.com/googleapis/gax-go/v2"
	"google.golang.org/api/option"
	"google.golang.org/api/option/internaloption"
	gtransport "google.golang.org/api/transport/grpc"
	resourcespb "google.golang.org/genproto/googleapis/ads/googleads/v7/resources"
	servicespb "google.golang.org/genproto/googleapis/ads/googleads/v7/services"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
)

var newKeywordPlanAdGroupKeywordClientHook clientHook

// KeywordPlanAdGroupKeywordCallOptions contains the retry settings for each method of KeywordPlanAdGroupKeywordClient.
type KeywordPlanAdGroupKeywordCallOptions struct {
	GetKeywordPlanAdGroupKeyword     []gax.CallOption
	MutateKeywordPlanAdGroupKeywords []gax.CallOption
}

func defaultKeywordPlanAdGroupKeywordClientOptions() []option.ClientOption {
	return []option.ClientOption{
		internaloption.WithDefaultEndpoint("googleads.googleapis.com:443"),
		internaloption.WithDefaultMTLSEndpoint("googleads.mtls.googleapis.com:443"),
		internaloption.WithDefaultAudience("https://googleads.googleapis.com/"),
		internaloption.WithDefaultScopes(DefaultAuthScopes()...),
		option.WithGRPCDialOption(grpc.WithDisableServiceConfig()),
		option.WithGRPCDialOption(grpc.WithDefaultCallOptions(
			grpc.MaxCallRecvMsgSize(math.MaxInt32))),
	}
}

func defaultKeywordPlanAdGroupKeywordCallOptions() *KeywordPlanAdGroupKeywordCallOptions {
	return &KeywordPlanAdGroupKeywordCallOptions{
		GetKeywordPlanAdGroupKeyword: []gax.CallOption{
			gax.WithRetry(func() gax.Retryer {
				return gax.OnCodes([]codes.Code{
					codes.Unavailable,
					codes.DeadlineExceeded,
				}, gax.Backoff{
					Initial:    5000 * time.Millisecond,
					Max:        60000 * time.Millisecond,
					Multiplier: 1.30,
				})
			}),
		},
		MutateKeywordPlanAdGroupKeywords: []gax.CallOption{
			gax.WithRetry(func() gax.Retryer {
				return gax.OnCodes([]codes.Code{
					codes.Unavailable,
					codes.DeadlineExceeded,
				}, gax.Backoff{
					Initial:    5000 * time.Millisecond,
					Max:        60000 * time.Millisecond,
					Multiplier: 1.30,
				})
			}),
		},
	}
}

// KeywordPlanAdGroupKeywordClient is a client for interacting with Google Ads API.
//
// Methods, except Close, may be called concurrently. However, fields must not be modified concurrently with method calls.
type KeywordPlanAdGroupKeywordClient struct {
	// Connection pool of gRPC connections to the service.
	connPool gtransport.ConnPool

	// flag to opt out of default deadlines via GOOGLE_API_GO_EXPERIMENTAL_DISABLE_DEFAULT_DEADLINE
	disableDeadlines bool

	// The gRPC API client.
	keywordPlanAdGroupKeywordClient servicespb.KeywordPlanAdGroupKeywordServiceClient

	// The call options for this service.
	CallOptions *KeywordPlanAdGroupKeywordCallOptions

	// The x-goog-* metadata to be sent with each request.
	xGoogMetadata metadata.MD
}

// NewKeywordPlanAdGroupKeywordClient creates a new keyword plan ad group keyword service client.
//
// Service to manage Keyword Plan ad group keywords. KeywordPlanAdGroup is
// required to add ad group keywords. Positive and negative keywords are
// supported. A maximum of 10,000 positive keywords are allowed per keyword
// plan. A maximum of 1,000 negative keywords are allower per keyword plan. This
// includes campaign negative keywords and ad group negative keywords.
func NewKeywordPlanAdGroupKeywordClient(ctx context.Context, opts ...option.ClientOption) (*KeywordPlanAdGroupKeywordClient, error) {
	clientOpts := defaultKeywordPlanAdGroupKeywordClientOptions()

	if newKeywordPlanAdGroupKeywordClientHook != nil {
		hookOpts, err := newKeywordPlanAdGroupKeywordClientHook(ctx, clientHookParams{})
		if err != nil {
			return nil, err
		}
		clientOpts = append(clientOpts, hookOpts...)
	}

	disableDeadlines, err := checkDisableDeadlines()
	if err != nil {
		return nil, err
	}

	connPool, err := gtransport.DialPool(ctx, append(clientOpts, opts...)...)
	if err != nil {
		return nil, err
	}
	c := &KeywordPlanAdGroupKeywordClient{
		connPool:         connPool,
		disableDeadlines: disableDeadlines,
		CallOptions:      defaultKeywordPlanAdGroupKeywordCallOptions(),

		keywordPlanAdGroupKeywordClient: servicespb.NewKeywordPlanAdGroupKeywordServiceClient(connPool),
	}
	c.setGoogleClientInfo()

	return c, nil
}

// Connection returns a connection to the API service.
//
// Deprecated.
func (c *KeywordPlanAdGroupKeywordClient) Connection() *grpc.ClientConn {
	return c.connPool.Conn()
}

// Close closes the connection to the API service. The user should invoke this when
// the client is no longer required.
func (c *KeywordPlanAdGroupKeywordClient) Close() error {
	return c.connPool.Close()
}

// setGoogleClientInfo sets the name and version of the application in
// the `x-goog-api-client` header passed on each request. Intended for
// use by Google-written clients.
func (c *KeywordPlanAdGroupKeywordClient) setGoogleClientInfo(keyval ...string) {
	kv := append([]string{"gl-go", versionGo()}, keyval...)
	kv = append(kv, "gapic", versionClient, "gax", gax.Version, "grpc", grpc.Version)
	c.xGoogMetadata = metadata.Pairs("x-goog-api-client", gax.XGoogHeader(kv...))
}

// GetKeywordPlanAdGroupKeyword returns the requested Keyword Plan ad group keyword in full detail.
//
// List of thrown errors:
// AuthenticationError (at )
// AuthorizationError (at )
// HeaderError (at )
// InternalError (at )
// QuotaError (at )
// RequestError (at )
func (c *KeywordPlanAdGroupKeywordClient) GetKeywordPlanAdGroupKeyword(ctx context.Context, req *servicespb.GetKeywordPlanAdGroupKeywordRequest, opts ...gax.CallOption) (*resourcespb.KeywordPlanAdGroupKeyword, error) {
	if _, ok := ctx.Deadline(); !ok && !c.disableDeadlines {
		cctx, cancel := context.WithTimeout(ctx, 3600000*time.Millisecond)
		defer cancel()
		ctx = cctx
	}
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "resource_name", url.QueryEscape(req.GetResourceName())))
	ctx = insertMetadata(ctx, c.xGoogMetadata, md)
	opts = append(c.CallOptions.GetKeywordPlanAdGroupKeyword[0:len(c.CallOptions.GetKeywordPlanAdGroupKeyword):len(c.CallOptions.GetKeywordPlanAdGroupKeyword)], opts...)
	var resp *resourcespb.KeywordPlanAdGroupKeyword
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = c.keywordPlanAdGroupKeywordClient.GetKeywordPlanAdGroupKeyword(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// MutateKeywordPlanAdGroupKeywords creates, updates, or removes Keyword Plan ad group keywords. Operation
// statuses are returned.
//
// List of thrown errors:
// AuthenticationError (at )
// AuthorizationError (at )
// DatabaseError (at )
// FieldError (at )
// HeaderError (at )
// InternalError (at )
// KeywordPlanAdGroupKeywordError (at )
// KeywordPlanError (at )
// MutateError (at )
// QuotaError (at )
// RequestError (at )
// ResourceCountLimitExceededError (at )
func (c *KeywordPlanAdGroupKeywordClient) MutateKeywordPlanAdGroupKeywords(ctx context.Context, req *servicespb.MutateKeywordPlanAdGroupKeywordsRequest, opts ...gax.CallOption) (*servicespb.MutateKeywordPlanAdGroupKeywordsResponse, error) {
	if _, ok := ctx.Deadline(); !ok && !c.disableDeadlines {
		cctx, cancel := context.WithTimeout(ctx, 3600000*time.Millisecond)
		defer cancel()
		ctx = cctx
	}
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "customer_id", url.QueryEscape(req.GetCustomerId())))
	ctx = insertMetadata(ctx, c.xGoogMetadata, md)
	opts = append(c.CallOptions.MutateKeywordPlanAdGroupKeywords[0:len(c.CallOptions.MutateKeywordPlanAdGroupKeywords):len(c.CallOptions.MutateKeywordPlanAdGroupKeywords)], opts...)
	var resp *servicespb.MutateKeywordPlanAdGroupKeywordsResponse
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = c.keywordPlanAdGroupKeywordClient.MutateKeywordPlanAdGroupKeywords(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
